#%RAML 1.0 NamedExample
example:
    customer id: 1
    customer name: Alfreds Futterkiste 
    contactname: Maria Anders
    address: obere Str.57
    city: berlin
    postal code: 12209
    country: "Germany"

       customer id: 2
       customer name: Ana Trujillo Emparedados y helados
       contactname: Ana Trujillo
       address: Avda.de la Constitucion 2222 
       city: mexico D.F.
       postal code: 05021
       country: mexico
    
  
  
    
  
  