#%RAML 1.0 DataType

type:
  properties:
    customer id: number
    customer name: string
    contactname: string
    address: string
    city: string
    postal code: number
    country: string
    
